### ISSUE TITLE
Incorrect PHP version requirement

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-app-advanced#440]
### What steps will reproduce the problem?
Attempt to develop an application using this template on PHP 5.6:

1. `git clone git@github.com:yiisoft/yii2-app-advanced.git`
2. Alter `composer.json` to use PHP 5.6:
```
"config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        },
	"platform": {
            "php": "5.6.0"
	}
    },
```
3. `composer install`

### What's expected?
It should work

### What do you get instead?
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeception/verify ~1.1.0 -> satisfiable by codeception/verify[1.1.0].
    - codeception/verify 1.1.0 requires php >= 7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
  Problem 2
    - phpunit/phpunit 6.5.9 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.8 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.7 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.6 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.5 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.14 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.13 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.12 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.11 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - phpunit/phpunit 6.5.10 requires php ^7.0 -> your PHP version (7.3.4-1+ubuntu18.04.1+deb.sury.org+3) overridden by "config.platform.php" version (5.6.0) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ~6.5.5 -> satisfiable by phpunit/phpunit[6.5.10, 6.5.11, 6.5.12, 6.5.13, 6.5.14, 6.5.5, 6.5.6, 6.5.7, 6.5.8, 6.5.9].

```
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
I think we are using Codeception version that is not compatible with 5.6 with advanced app.

**Comment by SamMousa** [comment]
Yes, that's why the PHP version requirement is no longer correct

**Comment by samdark** [comment]
Fixed by @Naktibalda.

**Comment by Naktibalda** [comment]
@samdark Actually this issue is still valid, composer.json says that the lowest supported version of PHP is 5.4.0, but the some tests fail on versions lower than 5.6.0
